const FETCH_EMPLOYEES_REQUEST = "FETCH_EMPLOYEES_REQUEST";
const FETCH_EMPLOYEES_SUCCESS = "FETCH_EMPLOYEES_SUCCESS";
const FETCH_EMPLOYEESID_SUCCESS = "FETCH_EMPLOYEESID_SUCCESS";
const FETCH_EMPLOYEES_FAILURE = "FETCH_EMPLOYEES_FAILURE";



export { FETCH_EMPLOYEES_REQUEST, FETCH_EMPLOYEES_SUCCESS, FETCH_EMPLOYEES_FAILURE,  FETCH_EMPLOYEESID_SUCCESS };